module RetentionPlanRules
  STANDARD_RETENTION_DAYS = 42
  GOLD_RETENTION_DAYS = 42
  GOLD_LAST_SNAPSHOT_MONTHS_RETENTION = 12
  PLATINUM_RETENTION_DAYS = 42
  PLATINUM_LAST_SNAPSHOT_MONTHS_RETENTION = 12
  PLATINUM_LAST_SNAPSHOT_YEARS_RETENTION = 7
end
